languageCode = "en"
languageName = "English"
weight = 1

title = "Abantika Bhuti"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Abantika Bhuti"
  image = "img/main-image.png"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:abantika.bhuti@gmail.com" },
    { link = "https://awkwardquill.wordpress.com/" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    { github = "https://github.com/abantikabhuti" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { hashnode = "https://username.hashnode.dev" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/abantikabhuti" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { orcid = "https://orcid.org/userid" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    # { ko-fi = "https://ko-fi.com/username" },
  ]
