languageCode = "en"
languageName = "English"
weight = 1

title = "Abantika Bhuti"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  # description = "research assistant"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Abantika Bhuti"
  image = "img/main-image.png"
  # headline = "research assistant"
  # bio = "research assistant"
  links = [
    { envelope = "mailto:abantika.bhuti@gmail.com" },
    # { link = "https://awkwardquill.wordpress.com/" },
    { github = "https://github.com/abantikabhuti" },
    { linkedin = "https://linkedin.com/in/abantikabhuti" },
    # { orcid = "https://orcid.org/userid" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # google-scholar
    # arxiv
  ]
